### ISSUE TITLE
When will the IEPD template be upgraded to NIEM 5?

### ISSUE THREAD

**Issue by leilatite** [NIEM/Template-IEPD#5]
Is this going to be replaced by something else, or is there a rebranding happening?

**Comment by cdmgtri** [comment]
Apologies for the delay!  We expect to have an updated IEPD template for 5.0 within the next couple of weeks.

**Comment by cdmgtri** [comment]
Sorry for the delay!  The template has been updated for 5.0 - https://github.com/NIEM/Template-IEPD/tree/niem-5.0.
